name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        run: |
          echo "REPOSITORY_OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-api:${{ github.sha }}
          cache-from: type=gha,scope=api
          cache-to: type=gha,scope=api,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-frontend:${{ github.sha }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,scope=frontend,mode=max

      - name: Build and push Relationship API image
        uses: docker/build-push-action@v5
        with:
          context: ./rel_api
          file: ./rel_api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-rel-api:${{ github.sha }}
          cache-from: type=gha,scope=rel-api
          cache-to: type=gha,scope=rel-api,mode=max

      - name: Build and push Reddit Crawler image
        uses: docker/build-push-action@v5
        with:
          context: ./reddit_crawler
          file: ./reddit_crawler/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-reddit-crawler:${{ github.sha }}
          cache-from: type=gha,scope=reddit-crawler
          cache-to: type=gha,scope=reddit-crawler,mode=max

      - name: Build and push NER API image
        uses: docker/build-push-action@v5
        with:
          context: ./ner_api
          file: ./ner_api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-ner-api:${{ github.sha }}
          cache-from: type=gha,scope=ner-api
          cache-to: type=gha,scope=ner-api,mode=max

      - name: Build and push Code RAG image
        uses: docker/build-push-action@v5
        with:
          context: ./code_rag
          file: ./code_rag/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/graphrag-code-rag:${{ github.sha }}
          cache-from: type=gha,scope=code-rag
          cache-to: type=gha,scope=code-rag,mode=max 